### ISSUE TITLE
[Team 2] Create UML diagrams

### ISSUE THREAD

**Issue by gang525** [bkochuna/ners570f21-Lab06#15]
**About**
This isssue tracks the creation of the UML diagram images. UML diagrams aid in developing a plan for how to design the interface.

**Tasks**
Diagrams should capture
- [ ] Class -- should capture conceptual modeling of structure of the system and sometimes detailed modeling
- [ ] Sequence -- show order of interaction in code @gang525 
- [ ] State -- show behavior of specific object with sequence of events that the object endures throughout its lifetime
- [ ] Communication -- relationship of objects (very similar to sequence diagram)
[descriptions taken from here](https://gitmind.com/uml-diagram-types.html#_1)
The diagrams will capture different objects that are in the system and how they interact with each other. They are being created to visualize the objects and their interactions.

The data types and structures in our high-level design
- [ ] Document datatypes (double & single) in diagram

Each diagram should provide and interface to returning or defining matrices in all of the formats
- [ ] COO
- [ ] CRS
- [ ] BCRS
- [ ] JDS
- [ ] ELLPACK

Methods
- [ ] Diagram should provide an interface to perform spare matrix vector multiplication

**Definition of Done**
Finished when the boxes are ticked. Provide UML diagrams (give link to your diagram by editing this issue).
Reviewed by at least 3 other people.

Please put your name next to the task you're taking.
